import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>AKAZA POLL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-3xl font-bold underline">Hello, World</div>
    </>
  );
}
